### PR TITLE
Discoranged

### PR DESCRIPTION
**Pull request by jneilliii**
An orange themed version of your original Discord implementation with a couple of tweaks.

### CODE REVIEW

**Comment by jneilliii** [comment]
Sorry for all the commits, I use github to transfer my changes to my pi as I develop rather than developing locally.

**Comment by Birkbjo** [comment]
No problem, I will just squash it. 

Will probably do a release with this the following Wednesday, but I currently have no time to test this before that.

**Comment by Birkbjo** [comment]
I will also try to look into changing variable names to e.g (primaryColor) for the discorded-theme, so it's easier to just override the color, instead of having to duplicate and override all the selectors.

**Comment by ThorstenWirth** [comment]
I really like the Discoranged-Theme.
But i think this theme would also look great with light-green headers. A not too dark violet, blue or a nice and deep red might also be nice.

**Comment by Birkbjo** [comment]
You can do this yourself through the customization .

**Pull request merged**
